version: 2

before:
  hooks:
    - go mod download

builds:
  - id: epoch-debug
    binary: epoch.dbg
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/cocoonstack/epoch/version.Revision={{.Commit}}
      - -X github.com/cocoonstack/epoch/version.Version={{.Env.VERSION}}
      - -X github.com/cocoonstack/epoch/version.BuiltAt={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
    main: .

  - id: epoch-linux
    binary: epoch
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -X github.com/cocoonstack/epoch/version.Revision={{.Commit}}
      - -X github.com/cocoonstack/epoch/version.Version={{.Env.VERSION}}
      - -X github.com/cocoonstack/epoch/version.BuiltAt={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: .

archives:
  - id: release
    builds:
      - epoch-linux
    name_template: >-
      {{- .ProjectName }}_{{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

  - id: debug
    builds:
      - epoch-debug
    name_template: >-
      {{- .ProjectName }}_{{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}_debug
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
